/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){CKEDITOR.dialog.add("link",function(f){function w(a,b){var d=a.createRange();d.setStartBefore(b);d.setEndAfter(b);return d}var p=CKEDITOR.plugins.link,t,v=function(){var a=this.getDialog(),b=a.getContentElement("target","popupFeatures"),a=a.getContentElement("target","linkTargetName"),d=this.getValue();if(b&&a)switch(b=b.getElement(),b.hide(),a.setValue(""),d){case "frame":a.setLabel(f.lang.a11ylink.targetFrameName);a.getElement().show();break;case "popup":b.show();a.setLabel(f.lang.a11ylink.targetPopupName);
a.getElement().show();break;default:a.setValue(d),a.getElement().hide()}},h=function(a){a.target&&this.setValue(a.target[this.id]||"")},k=function(a){a.advanced&&this.setValue(a.advanced[this.id]||"")},m=function(a){a.target||(a.target={});a.target[this.id]=this.getValue()||""},n=function(a){a.advanced||(a.advanced={});a.advanced[this.id]=this.getValue()||""},r=function(a){return a.trim().toLowerCase().replace(/^\s*|\s(?=\s)|\s*$/g,"")},g=f.lang.common,b=f.lang.a11ylink,c;return{title:b.title,minWidth:"moono-lisa"==
(CKEDITOR.skinName||f.config.skin)?450:350,minHeight:220,contents:[{id:"info",label:b.info,title:b.info,elements:[{type:"vbox",align:"bottom",id:"linkDisplayTextOptions",children:[{type:"hbox",widths:["85%","15%"],children:[{type:"text",id:"linkDisplayText",label:b.displayText,title:b.displayTextTitle,setup:function(){this.enable();this.setValue(f.getSelection().getSelectedText());t=this.getValue()},validate:function(){var a=this.getDialog().getContentElement("info","linkType").getValue(),q="url"===
a,d="email"===a,l="anchor"===a,a=this.getValue(),e;e=a.trim().toLowerCase().replace(/^\s*|\s(?=\s)|\s*$/g,"").replace(/^https?\:\/\//i,"");e=e.replace(/[.,!?]+$/,"");var c=0===e.length,g=0===a.toLowerCase().indexOf("http"),u=this.getDialog().getContentElement("info","url").getValue(),u=r(u),h=this.getDialog().getContentElement("info","emailAddress").getValue(),h=r(h),k=this.getDialog().getContentElement("info","anchorName").getValue(),k=r(k)===e,m=this.getDialog().getContentElement("info","anchorId").getValue();
r(m);if(q){if(c)return alert(b.msgEmptyDisplayText),!1;if(e===u||g)return confirm(b.msgUrlDisplayText)}if(l){q=p.getEditorAnchors(f);if(c)return alert(b.msgEmptyDisplayText),!1;if(k||k)return confirm(b.msgNameEqualToDisplayText);q&&0!==q.length||alert(b.msgNoAnchors)}if(d){if(c)return alert(b.msgEmptyDisplayText),!1;if(h===e)return confirm(b.msgEmailDisplayText)}for(d=0;d<b.a11yFirstInvalidDisplayText.length;d++)if(e===b.a11yFirstInvalidDisplayText[d])return alert(b.msgInvalidDisplayText.replace("%s",
a)),!1;for(d=0;d<b.a11yFirstInvalidStartText.length;d++)if(0===e.indexOf(b.a11yFirstInvalidStartText[d]))return alert(b.msgInvalidStartText.replace("%s",b.a11yFirstInvalidStartText[d])),!1;return!0},commit:function(a){a.linkText=this.isEnabled()?this.getValue():""}},{id:"a11yfirstHelpLink",type:"button",label:b.a11yfirstHelp,title:b.a11yfirstHelpTitle,onClick:function(){CKEDITOR.plugins.get("a11yfirsthelp")?(f.a11yfirst.helpOption="LinkHelp",f.execCommand("a11yFirstHelpDialog")):alert(b.helpNotFound)}}]}]},
{id:"linkTypeFieldset",type:"fieldset",label:b.type,children:[{id:"linkType",type:"radio","default":"url",items:[[b.toUrl,"url"],[b.toEmail,"email"],[b.toAnchor,"anchor"]],onChange:function(){var a=this.getDialog(),b=["urlOptions","anchorOptions","emailOptions"],d=this.getValue(),l=a.definition.getContents("upload"),l=l&&l.hidden;"url"==d?(f.config.linkShowTargetTab&&a.showPage("target"),l||a.showPage("upload")):(a.hidePage("target"),l||a.hidePage("upload"));for(l=0;l<b.length;l++){var e=a.getContentElement("info",
b[l]);e&&(e=e.getElement().getParent().getParent(),b[l]==d+"Options"?e.show():e.hide())}a.layout()},setup:function(a){this.getElement().addClass("a11yfirst_no_label");this.setValue(a.type||"url")},commit:function(a){a.type=this.getValue()}}]},{type:"vbox",id:"urlOptions",children:[{type:"hbox",widths:["25%","75%"],children:[{id:"protocol",type:"select",label:g.protocol,"default":"http://",items:[["http://‎","http://"],["https://‎","https://"],["ftp://‎","ftp://"],["news://‎","news://"],[b.other,""]],
setup:function(a){a.url&&this.setValue(a.url.protocol||"")},commit:function(a){a.url||(a.url={});a.url.protocol=this.getValue()}},{type:"text",id:"url",label:g.url,required:!0,onLoad:function(){this.allowOnChange=!0},onKeyUp:function(){this.allowOnChange=!1;var a=this.getDialog().getContentElement("info","protocol"),b=this.getValue(),d=/^((javascript:)|[#\/\.\?])/i,l=/^(http|https|ftp|news):\/\/(?=.)/i.exec(b);l?(this.setValue(b.substr(l[0].length)),a.setValue(l[0].toLowerCase())):d.test(b)&&a.setValue("");
this.allowOnChange=!0},onChange:function(){if(this.allowOnChange)this.onKeyUp()},validate:function(){var a=this.getDialog();return a.getContentElement("info","linkType")&&"url"!=a.getValueOf("info","linkType")?!0:!f.config.linkJavaScriptLinksAllowed&&/javascript\:/.test(this.getValue())?(alert(g.invalidValue),!1):this.getDialog().fakeObj?!0:CKEDITOR.dialog.validate.notEmpty(b.noUrl).apply(this)},setup:function(a){this.allowOnChange=!1;a.url&&this.setValue(a.url.url);this.allowOnChange=!0},commit:function(a){this.onChange();
a.url||(a.url={});a.url.url=this.getValue();this.allowOnChange=!1}}],setup:function(){this.getDialog().getContentElement("info","linkType")||this.getElement().show()}},{type:"button",id:"browse",hidden:"true",filebrowser:"info:url",label:g.browseServer}]},{type:"vbox",id:"anchorOptions",width:260,align:"center",padding:0,children:[{type:"fieldset",id:"selectAnchorText",label:b.selectAnchor,setup:function(){c=p.getEditorAnchors(f);this.getElement()[c&&c.length?"show":"hide"]()},children:[{type:"hbox",
id:"selectAnchor",children:[{type:"select",id:"anchorName","default":"",label:b.anchorName,style:"width: 100%;",items:[[""]],setup:function(a){this.clear();this.add("");if(c)for(var b=0;b<c.length;b++)c[b].name&&this.add(c[b].name);a.anchor&&this.setValue(a.anchor.name);(a=this.getDialog().getContentElement("info","linkType"))&&"email"==a.getValue()&&this.focus()},commit:function(a){a.anchor||(a.anchor={});a.anchor.name=this.getValue()},validate:function(){var a=this.getValue(),f=this.getDialog().getContentElement("info",
"anchorId").getValue();if(c.length&&""===a&&""===f)return confirm(b.msgNoAnchorSelected)}},{type:"select",id:"anchorId","default":"",label:b.anchorId,style:"width: 100%;",items:[[""]],setup:function(a){this.clear();this.add("");if(c)for(var b=0;b<c.length;b++)c[b].id&&this.add(c[b].id);a.anchor&&this.setValue(a.anchor.id)},commit:function(a){a.anchor||(a.anchor={});a.anchor.id=this.getValue()}}],setup:function(){this.getElement()[c&&c.length?"show":"hide"]()}}]},{type:"html",id:"noAnchors",style:"text-align: center;",
html:'\x3cdiv role\x3d"note" tabIndex\x3d"-1"\x3e'+CKEDITOR.tools.htmlEncode(b.noAnchors)+"\x3c/div\x3e",focus:!0,setup:function(){this.getElement()[c&&c.length?"hide":"show"]()}}],setup:function(){this.getDialog().getContentElement("info","linkType")||this.getElement().hide()}},{type:"vbox",id:"emailOptions",padding:1,children:[{type:"text",id:"emailAddress",label:b.emailAddress,required:!0,onKeyUp:function(){var a=this.getDialog().getContentElement("info","emailIsDisplayText"),b=this.getDialog().getContentElement("info",
"linkDisplayText").getValue();updateEmailIsDisplayText(a,b,this.getValue())},validate:function(){var a=this.getDialog();return a.getContentElement("info","linkType")&&"email"==a.getValueOf("info","linkType")&&""!==a.getValueOf("info","linkDisplayText")?CKEDITOR.dialog.validate.notEmpty(b.noEmail).apply(this):!0},setup:function(a){a.email&&this.setValue(a.email.address);(a=this.getDialog().getContentElement("info","linkType"))&&"email"==a.getValue()&&this.select()},commit:function(a){a.email||(a.email=
{});a.email.address=this.getValue()}},{type:"text",id:"emailSubject",label:b.emailSubject,setup:function(a){a.email&&this.setValue(a.email.subject)},commit:function(a){a.email||(a.email={});a.email.subject=this.getValue()}},{type:"textarea",id:"emailBody",label:b.emailBody,rows:3,"default":"",setup:function(a){a.email&&this.setValue(a.email.body)},commit:function(a){a.email||(a.email={});a.email.body=this.getValue()}}],setup:function(){this.getDialog().getContentElement("info","linkType")||this.getElement().hide()}}]},
{id:"target",requiredContent:"a[target]",label:b.target,title:b.target,elements:[{type:"hbox",widths:["50%","50%"],children:[{type:"select",id:"linkTargetType",label:g.target,"default":"notSet",style:"width : 100%;",items:[[g.notSet,"notSet"],[b.targetFrame,"frame"],[b.targetPopup,"popup"],[g.targetNew,"_blank"],[g.targetTop,"_top"],[g.targetSelf,"_self"],[g.targetParent,"_parent"]],onChange:v,setup:function(a){a.target&&this.setValue(a.target.type||"notSet");v.call(this)},commit:function(a){a.target||
(a.target={});a.target.type=this.getValue()}},{type:"text",id:"linkTargetName",label:b.targetFrameName,"default":"",setup:function(a){a.target&&this.setValue(a.target.name)},commit:function(a){a.target||(a.target={});a.target.name=this.getValue().replace(/([^\x00-\x7F]|\s)/gi,"")}}]},{type:"vbox",width:"100%",align:"center",padding:2,id:"popupFeatures",children:[{type:"fieldset",label:b.popupFeatures,children:[{type:"hbox",children:[{type:"checkbox",id:"resizable",label:b.popupResizable,setup:h,commit:m},
{type:"checkbox",id:"status",label:b.popupStatusBar,setup:h,commit:m}]},{type:"hbox",children:[{type:"checkbox",id:"location",label:b.popupLocationBar,setup:h,commit:m},{type:"checkbox",id:"toolbar",label:b.popupToolbar,setup:h,commit:m}]},{type:"hbox",children:[{type:"checkbox",id:"menubar",label:b.popupMenuBar,setup:h,commit:m},{type:"checkbox",id:"fullscreen",label:b.popupFullScreen,setup:h,commit:m}]},{type:"hbox",children:[{type:"checkbox",id:"scrollbars",label:b.popupScrollBars,setup:h,commit:m},
{type:"checkbox",id:"dependent",label:b.popupDependent,setup:h,commit:m}]},{type:"hbox",children:[{type:"text",widths:["50%","50%"],labelLayout:"horizontal",label:g.width,id:"width",setup:h,commit:m},{type:"text",labelLayout:"horizontal",widths:["50%","50%"],label:b.popupLeft,id:"left",setup:h,commit:m}]},{type:"hbox",children:[{type:"text",labelLayout:"horizontal",widths:["50%","50%"],label:g.height,id:"height",setup:h,commit:m},{type:"text",labelLayout:"horizontal",label:b.popupTop,widths:["50%",
"50%"],id:"top",setup:h,commit:m}]}]}]}]},{id:"upload",label:b.upload,title:b.upload,hidden:!0,filebrowser:"uploadButton",elements:[{type:"file",id:"upload",label:g.upload,style:"height:40px",size:29},{type:"fileButton",id:"uploadButton",label:g.uploadSubmit,filebrowser:"info:url","for":["upload","upload"]}]},{id:"advanced",label:b.advanced,title:b.advanced,elements:[{type:"vbox",padding:1,children:[{type:"hbox",widths:["45%","35%","20%"],children:[{type:"text",id:"advId",requiredContent:"a[id]",
label:b.id,setup:k,commit:n},{type:"select",id:"advLangDir",requiredContent:"a[dir]",label:b.langDir,"default":"",style:"width:110px",items:[[g.notSet,""],[b.langDirLTR,"ltr"],[b.langDirRTL,"rtl"]],setup:k,commit:n},{type:"text",id:"advAccessKey",requiredContent:"a[accesskey]",width:"80px",label:b.acccessKey,maxLength:1,setup:k,commit:n}]},{type:"hbox",widths:["45%","35%","20%"],children:[{type:"text",label:b.name,id:"advName",requiredContent:"a[name]",setup:k,commit:n},{type:"text",label:b.langCode,
id:"advLangCode",requiredContent:"a[lang]",width:"110px","default":"",setup:k,commit:n},{type:"text",label:b.tabIndex,id:"advTabIndex",requiredContent:"a[tabindex]",width:"80px",maxLength:5,setup:k,commit:n}]}]},{type:"vbox",padding:1,children:[{type:"hbox",widths:["45%","55%"],children:[{type:"text",label:b.advisoryTitle,requiredContent:"a[title]","default":"",id:"advTitle",setup:k,commit:n},{type:"text",label:b.advisoryContentType,requiredContent:"a[type]","default":"",id:"advContentType",setup:k,
commit:n}]},{type:"hbox",widths:["45%","55%"],children:[{type:"text",label:b.cssClasses,requiredContent:"a(cke-xyz)","default":"",id:"advCSSClasses",setup:k,commit:n},{type:"text",label:b.charset,requiredContent:"a[charset]","default":"",id:"advCharset",setup:k,commit:n}]},{type:"hbox",widths:["45%","55%"],children:[{type:"text",label:b.rel,requiredContent:"a[rel]","default":"",id:"advRel",setup:k,commit:n},{type:"text",label:b.styles,requiredContent:"a{cke-xyz}","default":"",id:"advStyles",validate:CKEDITOR.dialog.validate.inlineStyle(f.lang.common.invalidInlineStyle),
setup:k,commit:n}]},{type:"hbox",widths:["45%","55%"],children:[{type:"checkbox",id:"download",requiredContent:"a[download]",label:b.download,setup:function(a){void 0!==a.download&&this.setValue("checked","checked")},commit:function(a){this.getValue()&&(a.download=this.getValue())}}]}]}]}],onShow:function(){var a=this.getParentEditor(),b=a.getSelection(),d=this.getContentElement("info","linkDisplayText").getElement().getParent().getParent(),f=p.getSelectedLink(a,!0),e=f[0]||null;e&&e.hasAttribute("href")&&
(b.getSelectedElement()||b.isInTable()||b.selectElement(e));b=p.parseLinkAttributes(a,e);1>=f.length&&p.showDisplayTextForElement(e,a)?d.show():d.hide();this._.selectedElements=f;this.setupContent(b)},onOk:function(){var a={};this.commitContent(a);if(this._.selectedElements.length){var b=this._.selectedElements,d=p.getLinkAttributes(f,a),l=[],e,c,k,g,h;for(h=0;h<b.length;h++){e=b[h];c=e.data("cke-saved-href");k=e.getHtml();e.setAttributes(d.set);e.removeAttributes(d.removed);if(a.linkText&&t!=a.linkText)g=
a.linkText;else if(c==k||"email"==a.type&&-1!=k.indexOf("@"))g="email"==a.type?a.email.address:d.set["data-cke-saved-href"];g&&e.setText(g);l.push(w(f,e))}f.getSelection().selectRanges(l);delete this._.selectedElements}else{b=p.getLinkAttributes(f,a);d=f.getSelection().getRanges();l=new CKEDITOR.style({element:"a",attributes:b.set});e=[];l.type=CKEDITOR.STYLE_INLINE;for(k=0;k<d.length;k++){c=d[k];c.collapsed?(g=new CKEDITOR.dom.text(a.linkText||("email"==a.type?a.email.address:b.set["data-cke-saved-href"]),
f.document),c.insertNode(g),c.selectNodeContents(g)):t!==a.linkText&&(g=new CKEDITOR.dom.text(a.linkText,f.document),c.shrink(CKEDITOR.SHRINK_TEXT),f.editable().extractHtmlFromRange(c),c.insertNode(g));g=c._find("a");for(h=0;h<g.length;h++)g[h].remove(!0);l.applyToRange(c,f);e.push(c)}f.getSelection().selectRanges(e)}},onLoad:function(){f.config.linkShowAdvancedTab||this.hidePage("advanced");f.config.linkShowTargetTab||this.hidePage("target");this.getElement().addClass("a11ylink_dialog")},onFocus:function(){var a=
this.getContentElement("info","linkType");a&&"url"==a.getValue()&&(a=this.getContentElement("info","linkDisplayText"),a.select())}}})})();