/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){var r=[],h="h1 h2 h3 h4 h5 h6".split(" "),q=["p","pre","address","div"],d=[],t=[],u,m,v;CKEDITOR.plugins.add("a11yheading",{requires:"menubutton",onLoad:function(){CKEDITOR.document.appendStyleSheet(this.path+"styles/a11yheading.css")},init:function(a){function c(a,b){function e(a){return!isNaN(a)}for(var g=a.split("."),c=b.split(".");g.length<c.length;)g.push("0");for(;c.length<g.length;)c.push("0");CKEDITOR.tools.array.map(g,Number);CKEDITOR.tools.array.map(c,Number);if(!CKEDITOR.tools.array.every(g,
e)||!CKEDITOR.tools.array.every(c,e))return NaN;for(var d=0;d<g.length;d++)if(g[d]!=c[d])return g[d]>c[d]?1:-1;return 0}var b=a.lang.a11yheading;if(!a.blockless){a.on("panelShow",function(a){a=(a.data[0]||a.data).element.getElementsByTag("iframe").getItem(0).getFrameDocument().getElementsByTag("head").getItem(0);if(0===a.$.querySelectorAll("#a11yheading_menubutton").length){var b=document.createElement("style");b.setAttribute("type","text/css");b.setAttribute("id","a11yheading_menubutton");b.innerHTML=
".cke_menubutton_on .cke_menubutton_icon::after { content: '✓'; font-weight: bold; font-size: 110%; position: relative; left: -0.9em; top: .05em; } .cke_menubutton_disabled .cke_menubutton_label { opacity: 0.4; filter: alpha(opacity\x3d40); }";a.$.appendChild(b)}});-1===c(CKEDITOR.version,"4.11")&&(CKEDITOR.scriptLoader.load(this.path+"js/override.js"),console.log("Loaded override.js"));var e=a.config,b=a.lang.a11yheading,l=this,k={},f;d=this.getHeadingTags(e);m=(u="undefined"===typeof e.allow_only_one_h1?
!0:e.allow_only_one_h1)&&"h1"===d[0]?1:0;v=d.length-1;t=this.getFormatTags(e);a.addCommand("heading",{allowedContent:r,contextSensitive:!0,exec:function(a,b){var c=k[b];if(c)a[c.style.checkActive(a.elementPath(),a)?"removeStyle":"applyStyle"](c.style)},refresh:function(a){this.setState(l.getCurrentHeadingOrFormatElement(a)?CKEDITOR.TRISTATE_ON:CKEDITOR.TRISTATE_OFF)}});for(e=0;e<d.length;e++)f=d[e],k[f]={label:b["level_"+f],headingId:f,group:"heading_levels",style:new CKEDITOR.style({element:f}),
order:e,onClick:function(){a.execCommand("heading",this.headingId)},role:"menuitemcheckbox"},r.push(k[f].style);for(e=0;e<t.length;e++)f=t[e],k[f]={label:b["format_"+f],formatId:f,group:"block_formats",style:new CKEDITOR.style({element:f}),order:d.length+e,onClick:function(){a.execCommand("heading",this.formatId)},role:"menuitemcheckbox"},r.push(k[f].style);k.headingHelp={label:b.helpLabel,group:"help_items",order:d.length+t.length+1,onClick:function(){CKEDITOR.plugins.get("a11yfirsthelp")?(a.a11yfirst.helpOption=
"HeadingHelp",a.execCommand("a11yFirstHelpDialog")):alert(b.helpNotFound)}};a.addMenuGroup("heading_levels",1);a.addMenuGroup("block_formats",2);a.addMenuGroup("help_items");a.addMenuItems(k);a.ui.add("Heading",CKEDITOR.UI_MENUBUTTON,{label:b.label,title:b.panelTitle,allowedContent:r,toolbar:"heading",command:"heading",onMenu:function(){var b={},c=l.getAllowedHeadings(a),e=l.getCurrentHeadingOrFormatElement(a),g;for(g in k)l.isHeadingElement(g)?b[g]=-1==c.indexOf(g)?CKEDITOR.TRISTATE_DISABLED:CKEDITOR.TRISTATE_OFF:
b[g]=CKEDITOR.TRISTATE_OFF;b.headingHelp=CKEDITOR.TRISTATE_OFF;e&&(b[e.getName()]=CKEDITOR.TRISTATE_ON);return b}})}},isHeadingElement:function(a){return 0<=h.indexOf(a)},isFormatElement:function(a){return 0<=q.indexOf(a)},isHeadingOrFormatElement:function(a){return this.isHeadingElement(a)||this.isFormatElement(a)},getCurrentHeadingOrFormatElement:function(a){var c=a.elementPath();a=c&&c.elements;var b;if(c)for(var e=0;e<a.length;e++)c=a[e],!b&&this.isHeadingOrFormatElement(c.getName())&&(b=c);return b},
getHeadingTags:function(a){if("string"!==typeof a.format_tags||0===a.format_tags.length)return h.slice();var c=[];a=a.format_tags.split(";");for(var b=0;b<a.length;b++)a[b]=a[b].toLowerCase();for(b=0;b<h.length;b++){var e=h[b];0<=a.indexOf(e)&&c.push(e)}switch(c.length){case 0:return h.slice();case 1:return c;default:return a=h.indexOf(c[0]),c=h.indexOf(c[c.length-1])+1,h.slice(a,c)}},getFormatTags:function(a){if("string"!==typeof a.format_tags||0===a.format_tags.length)return q.slice();var c=[];
a=a.format_tags.split(";");for(var b=0;b<a.length;b++)a[b]=a[b].toLowerCase();for(b=0;b<q.length;b++){var e=q[b];0<=a.indexOf(e)&&c.push(e)}return 0==c.length?q.slice(0,3):c},getAllowedHeadings:function(a){function c(a){var b;if("function"!==typeof a.getName)return!1;if(a.equals(h))return!0;b=a.getName();e.isHeadingElement(b)&&(l=b);a=a.getChildren();b=a.count();for(var d=0;d<b;d++)if(c(a.getItem(d)))return!0;return!1}function b(a){var c;if("function"!==typeof a.getName)return!1;if(a.equals(h))return f=
!0,!1;c=a.getName();if(f&&e.isHeadingElement(c))return k=c,!0;a=a.getChildren();c=a.count();for(var d=0;d<c;d++)if(b(a.getItem(d)))return!0;return!1}var e=this,l=null,k=null,f=!1,h,p,n;h=a.getSelection().getStartElement();console.log("SELECTED ELEMENT: "+h.getName());c(a.document.getBody());console.log("PREV HEADING: "+l);b(a.document.getBody());console.log("NEXT HEADING: "+k);if(null===l)return u&&null!==a.document.findOne("h1")?[]:d.slice(0,1);a=d.indexOf(l);if(0<=a)return null===k?p=d.slice(m,
a+2):(n=d.indexOf(k),0<=n?(a<n&&(p=d.slice(Math.max(m,a),n+1)),a===n&&(p=d.slice(Math.max(m,a-1),a+2)),a>n&&(p=d.slice(Math.max(m,n-1),a+2))):p=d.slice(m,a+2)),p;if(l<d[0])return d.slice(m,m+1);if(l>d[v])return d.slice(m)}})})();CKEDITOR.config.format_tags="h1;h2;h3;h4;h5;h6;p;pre;address;div";