/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.dialog.add("a11yimage",function(e){function F(){var a=this.getValue().match(G);(a=!(!a||0===parseInt(a[1],10)))||alert(m.invalidLength.replace("%1",m[this.id]).replace("%2","px"));return a}function y(a){return a.trim().replace(/\s+/g," ")}function R(){function a(a,f){d.push(b.once(a,function(a){for(var b;b=d.pop();)b.removeListener();f(a)}))}var b=u.createElement("img"),d=[];return function(d,f,e){a("load",function(){var a=I(b);f.call(e,b,a.width,a.height)});a("error",function(){f(null)});
a("abort",function(){f(null)});b.setAttribute("src",(z.baseHref||"")+d+"?"+Math.random().toString(16).substring(2))}}function J(){var a=this.getValue();v(!1);a!==A.data.src?(K(a,function(a,b,H){v(!0);if(!a)return n(!1);k.setValue(!1===e.config.a11yimage_prefillDimensions?0:b);l.setValue(!1===e.config.a11yimage_prefillDimensions?0:H);w=b;x=H;n(L.checkHasNaturalRatio(a))}),p=!0):p?(v(!0),k.setValue(q),l.setValue(r),p=!1):v(!0)}function M(){if(g){var a=this.getValue();if(a&&(a.match(G)||n(!1),"0"!==
a)){var b="width"==this.id,d=q||w,e=r||x,a=b?Math.round(a/d*e):Math.round(a/e*d);isNaN(a)||(b?l:k).setValue(a)}}}function n(a){if(h){if("boolean"==typeof a){if(B)return;g=a}else a=k.getValue(),B=!0,(g=!g)&&a&&(a*=r/q,isNaN(a)||l.setValue(Math.round(a)));h[g?"removeClass":"addClass"]("cke_btn_unlocked");h.setAttribute("aria-checked",g);CKEDITOR.env.hc&&h.getChild(0).setHtml(g?CKEDITOR.env.ie?"■":"▣":CKEDITOR.env.ie?"□":"▢")}}function v(a){a=a?"enable":"disable";k[a]();l[a]()}var G=/(^\s*(\d+)(px)?\s*$)|^$/i,
N=CKEDITOR.tools.getNextId(),O=CKEDITOR.tools.getNextId(),b=e.lang.a11yimage,m=e.lang.common,S=(new CKEDITOR.template('\x3cdiv\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.lockRatio+'" class\x3d"cke_btn_locked" id\x3d"{lockButtonId}" role\x3d"checkbox"\x3e\x3cspan class\x3d"cke_icon"\x3e\x3c/span\x3e\x3cspan class\x3d"cke_label"\x3e'+b.lockRatio+'\x3c/span\x3e\x3c/a\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.resetSize+'" class\x3d"cke_btn_reset" id\x3d"{resetButtonId}" role\x3d"button"\x3e\x3cspan class\x3d"cke_label"\x3e'+
b.resetSize+"\x3c/span\x3e\x3c/a\x3e\x3c/div\x3e")).output({lockButtonId:N,resetButtonId:O}),L=CKEDITOR.plugins.a11yimage,z=e.config,C=!(!z.filebrowserImageBrowseUrl&&!z.filebrowserBrowseUrl),D=e.widgets.registered.image.features,I=L.getNatural,u,A,P,K,q,r,w,x,p,g,B,h,t,k,l,E,Q=[{id:"src",type:"text",label:m.url,title:b.urlTitle,onKeyup:J,onChange:J,setup:function(a){this.getDialog().getContentElement("info","src").getElement().addClass("a11yimage_src_url");this.setValue(a.data.src)},commit:function(a){a.setData("src",
this.getValue().trim())},validate:CKEDITOR.dialog.validate.notEmpty(b.urlMissing)}];C&&Q.push({type:"button",id:"browse",style:"display:inline-block;margin-top:14px;",align:"center",label:e.lang.common.browseServer,hidden:!0,filebrowser:"info:src"});return{title:b.title,minWidth:350,minHeight:100,onLoad:function(){u=this._.element.getDocument();K=R();this.getElement().addClass("a11yimage_dialog")},onShow:function(){A=this.widget;P=A.parts.image;p=B=g=!1;E=I(P);w=q=E.width;x=r=E.height},contents:[{id:"info",
label:b.infoTab,elements:[{type:"vbox",padding:0,children:[{type:"hbox",widths:["100%"],className:"cke_dialog_image_url",children:Q}]},{id:"accessibleDescriptions",type:"fieldset",label:"Accessible Descriptions",children:[{type:"hbox",align:"bottom",children:[{id:"altText",type:"text",label:b.altTextLabel,title:b.altTextTitle,setup:function(a){this.getDialog().getContentElement("info","altText").getElement().addClass("a11yimage_alt_text");var b=a.data.alt.split("; ");1<b.length?this.setValue(b[0]):
this.setValue(a.data.alt)},onKeyUp:function(a){a=this.getDialog().getContentElement("info","altTextNotRequiredCheckbox");this.getValue().match(/\S/g)&&a.setValue(!1)},validate:function(a){var c;a=this.getValue();var d=y(a).toLowerCase(),e=d.length;c=this.getDialog().getContentElement("info","altTextNotRequiredCheckbox").getValue();if(0===this.getDialog().getContentElement("info","src").getValue().length)return!0;if(c)return 0===e?confirm(b.msgAltTextNotRequired):confirm(b.msgAltTextWillBeRemoved);
if(0===e)return alert(b.msgAltEmpty),!1;if(e>b.alternativeTextMaxLength)return confirm(b.msgAltTooLong.replace("%s1",a.trim().length).replace("%s2",b.alternativeTextMaxLength));for(c=0;c<b.altContainsFilename.length;c++)if(f=b.altContainsFilename[c],0<=d.indexOf(f))return alert(b.msgAltPrefix+"\n\n"+b.msgAltContainsFilename.replace("%s",f)),!1;for(c=0;c<b.altIsInvalid.length;c++)if(d===b.altIsInvalid[c])return alert(b.msgAltPrefix+"\n\n"+b.msgAltIsInvalid.replace("%s",a)),!1;for(c=0;c<b.altStartsWithInvalid.length;c++)if(0===
d.indexOf(b.altStartsWithInvalid[c]))return alert(b.msgAltPrefix+"\n\n"+b.msgAltStartsWithInvalid.replace("%s",a.substring(0,b.altStartsWithInvalid[c].length))),!1;for(c=0;c<b.altEndsWithInvalid.length;c++){var f=b.altEndsWithInvalid[c];if(d.substring(e-f.length,e)===f)return alert(b.msgAltPrefix+"\n\n"+b.msgAltEndsWithInvalid),!1}return!0},commit:function(a){var c=this.getDialog().getContentElement("info","longDescSelect").getValue();this.getDialog().getContentElement("info","altTextNotRequiredCheckbox").getValue()&&
(this.setValue(""),a.setData("alt",""));var d=this.getValue().trim();if(d.length)switch(c){case "before":d+="; "+b.longDescBefore;break;case "after":d+="; "+b.longDescAfter;break;case "both":d+="; "+b.longDescBoth}a.setData("alt",d)}}]},{id:"altTextNotRequired",type:"hbox",children:[{type:"checkbox",id:"altTextNotRequiredCheckbox",label:b.altTextNotRequiredLabel,setup:function(a){this.getDialog().getContentElement("info","altTextNotRequired").getElement().addClass("a11yimage_alt_text_not_required");
var b=a.data.src;"string"===typeof a.data.src&&"string"===typeof a.data.alt&&(b=y(a.data.src),y(a.data.alt),0<b.length&&0===a.data.alt.length&&this.setValue(!0))},onChange:function(a){a=this.getDialog().getContentElement("info","altText");var b=a.getValue().trim();this.getDialog().getContentElement("info","longDescSelect");!0===this.getValue()?b.length&&a.disable():(a.enable(),a.focus())}}]},{id:"longDescription",type:"hbox",title:b.longDescTitle,children:[{type:"select",id:"longDescSelect",label:b.longDescLabel,
style:"width : 100%;",items:[[b.longDescOptionNo,"nodesc"],[b.longDescOptionYesBefore,"before"],[b.longDescOptionYesAfter,"after"],[b.longDescOptionYesBoth,"both"]]}],setup:function(a){this.getDialog().getContentElement("info","longDescription").getElement().addClass("a11yimage_long_description");var c=a.data.alt.split("; ");a=this.getInputElement().findOne("select").$;1<c.length?(c=c[1],a.value=c===b.longDescBefore?"before":c===b.longDescAfter?"after":c===b.longDescBoth?"both":"nodesc"):a.value=
"nodesc"},onChange:function(a){a=this.getInputElement().findOne("select").$;this.setValue(a.value)}},{id:"imageDescHelp",type:"button",label:b.imageDescHelpLabel,setup:function(){this.getDialog().getContentElement("info","imageDescHelp").getElement().addClass("a11yimage_desc_help")},onClick:function(){CKEDITOR.plugins.get("a11yfirsthelp")?(e.a11yfirst.helpOption="ImageHelp",e.execCommand("a11yFirstHelpDialog")):alert(b.helpNotFound)}}]},{id:"captionCheckbox",type:"hbox",children:[{type:"vbox",padding:0,
children:[{id:"hasCaption",type:"checkbox",label:b.captionLabel,title:b.captionTitle,requiredContent:D.caption.requiredContent,setup:function(a){this.getDialog().getContentElement("info","captionCheckbox").getElement().addClass("a11yimage_caption_checkbox");this.setValue(a.data.hasCaption)},commit:function(a){a.setData("hasCaption",this.getValue())}}]}]},{type:"hbox",style:"margin-top: 5px",widths:["25%","25%","50%"],requiredContent:D.dimension.requiredContent,children:[{id:"width",type:"text",width:"45px",
label:m.width,validate:F,onKeyUp:M,onLoad:function(){k=this},setup:function(a){this.setValue(a.data.width)},commit:function(a){a.setData("width",this.getValue())}},{id:"height",type:"text",width:"45px",label:m.height,validate:F,onKeyUp:M,onLoad:function(){l=this},setup:function(a){this.setValue(a.data.height)},commit:function(a){a.setData("height",this.getValue())}},{id:"lock",type:"html",style:"margin-top:18px;width:40px;height:20px;",onLoad:function(){function a(a){a.on("mouseover",function(){this.addClass("cke_btn_over")},
a);a.on("mouseout",function(){this.removeClass("cke_btn_over")},a)}var b=this.getDialog();h=u.getById(N);t=u.getById(O);h&&(b.addFocusable(h,8+C),h.on("click",function(a){n();a.data&&a.data.preventDefault()},this.getDialog()),a(h));t&&(b.addFocusable(t,9+C),t.on("click",function(a){p?(k.setValue(w),l.setValue(x)):(k.setValue(q),l.setValue(r));a.data&&a.data.preventDefault()},this),a(t))},setup:function(a){n(a.data.lock)},commit:function(a){a.setData("lock",g)},html:S}]},{id:"imageAlignFieldset",requiredContent:D.align.requiredContent,
type:"fieldset",label:m.align,children:[{type:"hbox",id:"alignment",children:[{id:"align",type:"radio",items:[[b.alignNone,"none"],[b.alignLeft,"left"],[b.alignCenter,"center"],[b.alignRight,"right"]],setup:function(a){this.setValue(a.data.align)},commit:function(a){a.setData("align",this.getValue())}}]}]}]},{id:"Upload",hidden:!0,filebrowser:"uploadButton",label:b.uploadTab,elements:[{type:"file",id:"upload",label:b.btnUpload,style:"height:40px"},{type:"fileButton",id:"uploadButton",filebrowser:"info:src",
label:b.btnUpload,"for":["Upload","upload"]}]}]}});